### ISSUE TITLE
updated npm run dev fails for local ui

### ISSUE THREAD

**Issue by adrianco** [adrianco/spigo#39]
This was working until I sync'd the updates to allow pinning and deleting

$ npm run dev

> simianviz@0.1.0 dev /Users/acockcroft/go/src/github.com/adrianco/spigo/ui
> gulp dev

[23:44:37] Using gulpfile ~/go/src/github.com/adrianco/spigo/ui/gulpfile.js
[23:44:37] Starting 'dev'...
[23:44:37] Starting 'build-dev'...
[23:44:37] Starting 'clean-dist'...
[23:44:37] gulp-notify: [Gulp notification] Client dist folder cleaned...
[23:44:37] Finished 'clean-dist' after 36 ms
[23:44:37] Starting 'lint'...
[23:44:37] Starting 'styles'...
[23:44:37] Starting 'copy-font-awesome-fonts'...
[23:44:37] Starting 'copy-google-fonts'...
[23:44:37] Starting 'copy-html'...
[23:44:37] Starting 'copy-json'...
[23:44:37] Starting 'bundle-app'...
[23:44:38] Finished 'copy-html' after 559 ms
[23:44:38] gulp-notify: [Gulp notification] Styles created...
[23:44:38] Finished 'styles' after 772 ms
[23:44:38] Finished 'copy-font-awesome-fonts' after 979 ms
[23:44:38] gulp-notify: [Error running Gulp] Build Error: 'force' is not defined.
[23:44:38] 'lint' errored after 1.08 s
[23:44:38] ESLintError in plugin 'gulp-eslint'
Message:
    'force' is not defined.
Details:
    fileName: /Users/acockcroft/go/src/github.com/adrianco/spigo/ui/js/lib/d3-pin-nodes.js
    lineNumber: 5
[23:44:38] 'dev' errored after 1.14 s
[23:44:38] Error: [object Object]
    at formatError (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/run-sequence/index.js:53:5)
    at Gulp.onError (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/run-sequence/index.js:60:4)
    at Gulp.emit (events.js:117:20)
[23:44:38] 'build-dev' errored after 1.12 s
[23:44:38] Error: [object Object]
    at formatError (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/run-sequence/index.js:53:5)
    at Gulp.onError (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/run-sequence/index.js:60:4)
    at Gulp.emit (events.js:117:20)
[23:44:38] 'build-dev' errored after 1.12 s
[23:44:38] Error: [object Object]
    at formatError (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/run-sequence/index.js:53:5)
    at Gulp.onError (/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/node_modules/run-sequence/index.js:60:4)
    at Gulp.emit (events.js:117:20)
[23:44:39] 
/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/js/lib/d3-collision-detection.js
  16:18  warning  Function 'anonymous' has a complexity of 6  complexity

/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/js/lib/d3-link-expander.js
  19:21  warning  Strings must use singlequote  quotes

/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/js/lib/d3-pin-nodes.js
   5:4  error    'force' is not defined                          no-undef
   6:3  error    Unnecessary semicolon                           no-extra-semi
  14:3  error    Unnecessary semicolon                           no-extra-semi
  17:0  warning  Line 17 exceeds the maximum line length of 120  max-len
  19:6  error    'force' is not defined                          no-undef
  20:3  error    Unnecessary semicolon                           no-extra-semi

/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/.gulp-tasks/bundle-app.js
  25:33  warning  Strings must use singlequote  quotes

/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/.gulp-tasks/lint.js
  22:33  warning  Strings must use singlequote  quotes

/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/.gulp-tasks/minify-app.js
  16:33  warning  Strings must use singlequote  quotes

/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/.gulp-tasks/minify-styles.js
  16:33  warning  Strings must use singlequote  quotes

/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/.gulp-tasks/styles.js
  14:33  warning  Strings must use singlequote  quotes

✖ 13 problems (5 errors, 8 warnings)

[23:44:39] Finished 'copy-google-fonts' after 1.65 s
[23:44:41] Finished 'copy-json' after 3.77 s
Cannot find module 'lodash.sortby' from '/Users/acockcroft/go/src/github.com/adrianco/spigo/ui/js/chart'

**Comment by kkemple** [comment]
make sure to run `npm install`
