### ISSUE TITLE
Error: Cannot find module 'gulp-notify'

### ISSUE THREAD

**Issue by basivireddy** [adrianco/spigo#61]
root@n42-poweredge-8:~/spigo/src/github.com/adrianco/spigo/ui# npm run dev

> simianviz@0.1.0 dev /root/spigo/src/github.com/adrianco/spigo/ui
> node_modules/.bin/gulp dev

Error: Cannot find module 'gulp-notify'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/spigo/src/github.com/adrianco/spigo/ui/.gulp-tasks/bundle-app.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by kkemple** [comment]
PR #62 should have resolved any issues with gulp and the build process, can you please update to latest and see if the issue persists?

**Comment by kkemple** [comment]
@basivireddy ^^
